sudo: required
services:
  - docker

before_install:
  - docker build -t millsmcilroy/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true millsmcilroy/react-test npm test

after_success:
  - docker build -t millsmcilroy/multi-client ./client
  - docker build -t millsmcilroy/multi-nginx ./nginx
  - docker build -t millsmcilroy/multi-server ./server
  - docker build -t millsmcilroy/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push them to docker hub
  - docker push millsmcilroy/multi-client
  - docker push millsmcilroy/multi-nginx
  - docker push millsmcilroy/multi-server
  - docker push millsmcilroy/multi-worker